### PR TITLE
permissions

### PR DESCRIPTION
**Pull request by xBeastMode**

### CODE REVIEW

**Comment by MichaelM04** [comment]
Damb your making me jealous now :)

**Comment by MichaelM04** [comment]
Wait I forgot I changed the code long ago I'll have to reupload it

**Comment by xBeastMode** [comment]
xD If you want, you can leave me this plugin to me, I'll code it and you submit it

**Comment by MichaelM04** [comment]
Nah I need the practice and I changed the entire code I forgot to put on github I'll do later

**Comment by xBeastMode** [comment]
Alright :D

**Pull request closed without merging**
